/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ufes.pss.weather_data_display_final.view;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;

/**
 *
 * @author dener
 */
public class ViewTelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewTelaPrincipal
     */
    public ViewTelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        jLabel19 = new javax.swing.JLabel();
        totalRegistros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(765, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel19.setText("Nº de Registros:");

        desktop.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktop.setLayer(totalRegistros, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopLayout.createSequentialGroup()
                .addComponent(jLabel19)
                .addGap(4, 4, 4)
                .addComponent(totalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 635, Short.MAX_VALUE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addContainerGap(436, Short.MAX_VALUE)
                .addGroup(desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(totalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        getContentPane().add(desktop);
        desktop.setBounds(0, 0, 770, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getTotalRegistros() {
        return totalRegistros;
    }

    public JDesktopPane getDesktop() {
        return desktop;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel totalRegistros;
    // End of variables declaration//GEN-END:variables
}
